### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by cesarkohl** [FilipeMata/clean_architecture_typescript_example#23]
Hey Filipe ✋ 

This is a great repository that I'm willing to give it a try.

Unfortunately the command `make setup` shows up the following error:

```
ERROR: Cannot find "/application/src/infrastructure/db/databases.json".
```

How could this be fixed?

Best,
Cesar

**Comment by FilipeMata** [comment]
Hi @cesarkohl! 

I missed a template file for this when releasing the project.
You can add a database.json file with the following content in you db folder:

```
