### ISSUE TITLE
Base-repository abstractFindAll

### ISSUE THREAD

**Issue by petrovick** [FilipeMata/clean_architecture_typescript_example#3]
There is a miss typing error at base-repository.ts file.
At certain point of abstractFindAll method, you check whether the entity was loaded or not, in that case it wasn't, then you should add to the entityMap list, and the given object should be entity instead of loaded(which should be null/undefined anyways).

Below is an example of how it should be in my point of view.
<img width="1132" alt="Screen Shot 2020-12-13 at 09 29 43" src="https://user-images.githubusercontent.com/6144263/102011854-beda6480-3d25-11eb-9fec-8e095843d92c.png">

Congrats for the architecture.

**Comment by FilipeMata** [comment]
Thank's @petrovick. Fixed!
